name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Build and push the Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.gitlab.com
          repository: heyatomdev/andreacw5
          tags: ${{ steps.get_version.outputs.VERSION }}
          always_pull: true

      - name: List Docker images
        run: docker images

      - name: Scan the Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'registry.gitlab.com/heyatomdev/andreacw5:${{ steps.get_version.outputs.VERSION }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
